#!/usr/bin/env python3
"""Regenerate self-hosted webfonts.

Скачивает woff2 у Google Fonts и генерит src/shared/styles/fonts.css.
Запуск:  python3 scripts/fonts/generate-fonts.py
Затем при необходимости обнови список preload в index.html (печатается в конце).

Зачем self-host: внешний @import к fonts.googleapis.com обнаруживался поздно и
давал FOUT (прыжок шрифта). Локальные файлы + preload в <head> готовы к первому
рендеру. unicode-range оставляет браузеру право не качать ненужные субсеты.
"""
import os
import re
import urllib.request

# Источник: те же семейства/веса, что использует дизайн-система
# (см. src/shared/styles/tokens/typography.scss).
GF_URL = ('https://fonts.googleapis.com/css2?'
          'family=Source+Sans+3:wght@300;400;500;600;700'
          '&family=JetBrains+Mono:wght@400;500;700&display=swap')
CHROME_UA = ('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
             '(KHTML, like Gecko) Chrome/120.0 Safari/537.36')

KEEP = {'latin', 'latin-ext', 'cyrillic'}
PRELOAD_SUBSET = 'latin'
# (family, weight), которые видны в первом экране → их пре-loadим.
PRELOAD = {('Source Sans 3', '400'), ('Source Sans 3', '600'),
           ('Source Sans 3', '700'), ('JetBrains Mono', '400')}
SLUG = {'Source Sans 3': 'source-sans-3', 'JetBrains Mono': 'jetbrains-mono'}

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))   # packages/homepage
WOFF_DIR = os.path.join(ROOT, 'public', 'fonts')
CSS_OUT = os.path.join(ROOT, 'src', 'shared', 'styles', 'fonts.css')


def fetch(url, ua=None):
    req = urllib.request.Request(url, headers={'User-Agent': ua or 'Mozilla/5.0'})
    return urllib.request.urlopen(req).read()


def main():
    os.makedirs(WOFF_DIR, exist_ok=True)
    css = fetch(GF_URL, CHROME_UA).decode('utf-8')

    # CSS идёт блоками: /* subset */ @font-face { ... }
    parts = re.split(r'/\*\s*([a-z-]+)\s*\*/', css)
    faces, preloads, seen = [], [], set()

    for i in range(1, len(parts), 2):
        subset = parts[i].strip()
        if subset not in KEEP:
            continue
        m = re.search(r'@font-face\s*{(.*?)}', parts[i + 1], re.S)
        if not m:
            continue
        b = m.group(1)
        fam = re.search(r"font-family:\s*'([^']+)'", b).group(1)
        weight = re.search(r'font-weight:\s*(\d+)', b).group(1)
        url = re.search(r'src:\s*url\((https://[^)]+)\)', b).group(1)
        urange = re.search(r'unicode-range:\s*([^;]+);', b).group(1).strip()

        fname = f'{SLUG[fam]}-{weight}-{subset}.woff2'
        if fname in seen:
            continue
        seen.add(fname)

        dest = os.path.join(WOFF_DIR, fname)
        if not os.path.exists(dest):
            open(dest, 'wb').write(fetch(url))
            print(f'downloaded {fname}')

        faces.append(
            "@font-face {\n"
            f"  font-family: '{fam}';\n"
            "  font-style: normal;\n"
            f"  font-weight: {weight};\n"
            "  font-display: swap;\n"
            f"  src: url('/fonts/{fname}') format('woff2');\n"
            f"  unicode-range: {urange};\n"
            "}"
        )
        if subset == PRELOAD_SUBSET and (fam, weight) in PRELOAD:
            preloads.append(
                f'  <link rel="preload" href="/fonts/{fname}" '
                'as="font" type="font/woff2" crossorigin />'
            )

    header = ("/* Self-hosted fonts. Generated by scripts/fonts/generate-fonts.py\n"
              "   from Google Fonts (Source Sans 3, JetBrains Mono).\n"
              "   Subsets: latin, latin-ext, cyrillic. unicode-range keeps the browser\n"
              "   from downloading files it doesn't need. Do not edit by hand. */\n\n")
    open(CSS_OUT, 'w', encoding='utf-8').write(header + "\n\n".join(faces) + "\n")

    print(f'\nwrote {len(faces)} @font-face -> {os.path.relpath(CSS_OUT, ROOT)}')
    print('\nPreload tags for index.html <head>:')
    print("\n".join(preloads))


if __name__ == '__main__':
    main()
